version: '3.8'

services:
  rag-backend:
    build: .
    container_name: vw-rag-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
